version: '3'
services:
  python3:
    build:
      context: ./
      dockerfile: Dockerfile-python
    container_name: 'tamaya_python3'
    working_dir: '/home/root/'
    tty: true
    volumes:
      - ./tamaya:/home/root/opt:cached
